"""initial TAMP schema"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "e2635e560400"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_codes",
        sa.Column("key", sa.String(length=300), nullable=False),
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("target", sa.String(length=254), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "parties",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "onboarding",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parties_email"), "parties", ["email"], unique=True)
    op.create_table(
        "rate_buckets",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_rate_buckets_expires"), "rate_buckets", ["expires"], unique=False)
    op.create_table(
        "audit",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_owner_id"), "audit", ["owner_id"], unique=False)
    op.create_table(
        "deliveries",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deliveries_owner_id"), "deliveries", ["owner_id"], unique=False)
    op.create_table(
        "loads",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_loads_owner_id"), "loads", ["owner_id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_owner_id"), "notifications", ["owner_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("party_id", sa.String(length=80), nullable=False),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["parties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(op.f("ix_sessions_expires"), "sessions", ["expires"], unique=False)
    op.create_index(op.f("ix_sessions_party_id"), "sessions", ["party_id"], unique=False)
    op.create_table(
        "trucks",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trucks_owner_id"), "trucks", ["owner_id"], unique=False)
    op.create_table(
        "uploads",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_uploads_owner_id"), "uploads", ["owner_id"], unique=False)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhooks_owner_id"), "webhooks", ["owner_id"], unique=False)
    op.create_table(
        "fuelLogs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("truck_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fuelLogs_owner_id"), "fuelLogs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_fuelLogs_truck_id"), "fuelLogs", ["truck_id"], unique=False)
    op.create_table(
        "maintenance",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("truck_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_maintenance_owner_id"), "maintenance", ["owner_id"], unique=False)
    op.create_index(op.f("ix_maintenance_truck_id"), "maintenance", ["truck_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("load_id", sa.String(length=80), nullable=False),
        sa.Column("truck_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_load_id"), "matches", ["load_id"], unique=False)
    op.create_index(op.f("ix_matches_owner_id"), "matches", ["owner_id"], unique=False)
    op.create_index(op.f("ix_matches_truck_id"), "matches", ["truck_id"], unique=False)
    op.create_index(
        "one_live_match_per_load",
        "matches",
        ["load_id"],
        unique=True,
        postgresql_where=sa.text("data->>'status' IN ('ACCEPTED', 'CONFIRMED')"),
    )
    op.create_table(
        "reservations",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("load_id", sa.String(length=80), nullable=False),
        sa.Column("truck_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["truck_id"],
            ["trucks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reservations_load_id"), "reservations", ["load_id"], unique=False)
    op.create_index(op.f("ix_reservations_owner_id"), "reservations", ["owner_id"], unique=False)
    op.create_index(op.f("ix_reservations_truck_id"), "reservations", ["truck_id"], unique=False)
    op.create_index(
        "one_reservation_per_load",
        "reservations",
        ["load_id"],
        unique=True,
        postgresql_where=sa.text("data->>'status' = 'RESERVED'"),
    )
    op.create_table(
        "acceptances",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("match_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_acceptances_match_id"), "acceptances", ["match_id"], unique=False)
    op.create_index(op.f("ix_acceptances_owner_id"), "acceptances", ["owner_id"], unique=False)
    op.create_table(
        "trips",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("match_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trips_match_id"), "trips", ["match_id"], unique=False)
    op.create_index(op.f("ix_trips_owner_id"), "trips", ["owner_id"], unique=False)
    op.create_index("one_active_trip_per_truck_match", "trips", ["match_id"], unique=True)
    op.create_table(
        "disputes",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("trip_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_disputes_owner_id"), "disputes", ["owner_id"], unique=False)
    op.create_index(op.f("ix_disputes_trip_id"), "disputes", ["trip_id"], unique=False)
    op.create_table(
        "proofs",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("load_id", sa.String(length=80), nullable=False),
        sa.Column("trip_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["loads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proofs_load_id"), "proofs", ["load_id"], unique=False)
    op.create_index(op.f("ix_proofs_owner_id"), "proofs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_proofs_trip_id"), "proofs", ["trip_id"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("owner_id", sa.String(length=80), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("trip_id", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["parties.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ratings_owner_id"), "ratings", ["owner_id"], unique=False)
    op.create_index(op.f("ix_ratings_trip_id"), "ratings", ["trip_id"], unique=False)
    op.create_index("one_rating_per_party_trip", "ratings", ["owner_id", "trip_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("one_rating_per_party_trip", table_name="ratings")
    op.drop_index(op.f("ix_ratings_trip_id"), table_name="ratings")
    op.drop_index(op.f("ix_ratings_owner_id"), table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_proofs_trip_id"), table_name="proofs")
    op.drop_index(op.f("ix_proofs_owner_id"), table_name="proofs")
    op.drop_index(op.f("ix_proofs_load_id"), table_name="proofs")
    op.drop_table("proofs")
    op.drop_index(op.f("ix_disputes_trip_id"), table_name="disputes")
    op.drop_index(op.f("ix_disputes_owner_id"), table_name="disputes")
    op.drop_table("disputes")
    op.drop_index("one_active_trip_per_truck_match", table_name="trips")
    op.drop_index(op.f("ix_trips_owner_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_match_id"), table_name="trips")
    op.drop_table("trips")
    op.drop_index(op.f("ix_acceptances_owner_id"), table_name="acceptances")
    op.drop_index(op.f("ix_acceptances_match_id"), table_name="acceptances")
    op.drop_table("acceptances")
    op.drop_index(
        "one_reservation_per_load",
        table_name="reservations",
        postgresql_where=sa.text("data->>'status' = 'RESERVED'"),
    )
    op.drop_index(op.f("ix_reservations_truck_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_owner_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_load_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(
        "one_live_match_per_load",
        table_name="matches",
        postgresql_where=sa.text("data->>'status' IN ('ACCEPTED', 'CONFIRMED')"),
    )
    op.drop_index(op.f("ix_matches_truck_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_owner_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_load_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_maintenance_truck_id"), table_name="maintenance")
    op.drop_index(op.f("ix_maintenance_owner_id"), table_name="maintenance")
    op.drop_table("maintenance")
    op.drop_index(op.f("ix_fuelLogs_truck_id"), table_name="fuelLogs")
    op.drop_index(op.f("ix_fuelLogs_owner_id"), table_name="fuelLogs")
    op.drop_table("fuelLogs")
    op.drop_index(op.f("ix_webhooks_owner_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_uploads_owner_id"), table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_trucks_owner_id"), table_name="trucks")
    op.drop_table("trucks")
    op.drop_index(op.f("ix_sessions_party_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_notifications_owner_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_loads_owner_id"), table_name="loads")
    op.drop_table("loads")
    op.drop_index(op.f("ix_deliveries_owner_id"), table_name="deliveries")
    op.drop_table("deliveries")
    op.drop_index(op.f("ix_audit_owner_id"), table_name="audit")
    op.drop_table("audit")
    op.drop_index(op.f("ix_rate_buckets_expires"), table_name="rate_buckets")
    op.drop_table("rate_buckets")
    op.drop_index(op.f("ix_parties_email"), table_name="parties")
    op.drop_table("parties")
    op.drop_table("email_codes")
    # ### end Alembic commands ###
